apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoin-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/KubernetesData/BitcoinData"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-core
  template:
    metadata:
      labels:
        app: bitcoin-core
    spec:
      containers:
        - name: bitcoin-core
          image: bitcoin-core:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8332
          resources:
            requests:
              memory: "16Gi"
              cpu: "8000m" # Request 8 cores
            limits:
              cpu: "16000m" # Limit to 16 cores to utilize half of your logical processors
              memory: "16Gi"
          volumeMounts:
            - mountPath: "/root/.bitcoin"
              name: bitcoin-volume
      volumes:
        - name: bitcoin-volume
          persistentVolumeClaim:
            claimName: bitcoin-data-claim


---

apiVersion: v1
kind: Service
metadata:
  name: bitcoin-core-service
spec:
  type: NodePort
  ports:
    - port: 8332
      targetPort: 8332
      nodePort: 30000
  selector:
    app: bitcoin-core
