[CmdletBinding()]
param(
    [ValidateSet('Preflight', 'Initialize', 'Configure', 'Verify', 'LaunchCommand')]
    [string] $Action = 'Preflight',
    [string] $EnvFile = '.env',
    [string] $ExpectedDatabase = 'bitcoin_enterprise',
    [int] $BackfillHeight = -1,
    [string] $BitcoindPath,
    [switch] $ConfirmInitialize,
    [switch] $ConfirmConfigUpdate,
    [switch] $ForceConfig
)

. (Join-Path $PSScriptRoot 'enterprise_pg17_common.ps1')

if ($ExpectedDatabase -cne 'bitcoin_enterprise') {
    throw 'This rollout is intentionally limited to bitcoin_enterprise.'
}
if ($BackfillHeight -lt -1) { throw 'BackfillHeight must be -1 (disabled) or non-negative.' }

$repoRoot = Get-EnterpriseRepoRoot
$sourceEnv = Resolve-EnterpriseRepoPath -Path $EnvFile -MustExist
[void] (Import-EnterprisePgEnv -Path $sourceEnv -ExpectedDatabase $ExpectedDatabase)
$runtimeRoot = Resolve-EnterpriseRepoPath -Path '.runtime'
$mainnetRoot = Join-Path $runtimeRoot 'mainnet'
$nodeDirectory = Join-Path $mainnetRoot 'node'
$blocksRoot = Join-Path $mainnetRoot 'blocks-root'
$runtimeEnv = Join-Path $mainnetRoot 'enterprise.env'
$configPath = Join-Path $nodeDirectory 'bitcoin.conf'
$spoolPath = Join-Path $nodeDirectory 'enterprise\block_spool'

function Convert-ToBitcoinConfigPath {
    param([string] $Path)
    return ([System.IO.Path]::GetFullPath($Path) -replace '\\', '/')
}

function Get-ExpectedConfig {
    $config = [ordered]@{
        'chain' = 'main'
        'server' = '1'
        'nosettings' = '1'
        'rpcbind' = '127.0.0.1'
        'rpcallowip' = '127.0.0.1'
        'listen' = '0'
        'listenonion' = '0'
        'discover' = '0'
        'natpmp' = '0'
        'disablewallet' = '1'
        'prune' = '20000'
        'dbcache' = '4096'
        'txindex' = '0'
        'coinstatsindex' = '1'
        'blockfilterindex' = '0'
        'peerblockfilters' = '0'
        'enterpriseindex' = '1'
        'enterprisebootstrapfrompostgres' = '1'
        'enterprisespoolmax' = '1024'
        'enterprisemempoolexport' = '0'
        'enterpriseconfig' = Convert-ToBitcoinConfigPath $runtimeEnv
        'blocksdir' = Convert-ToBitcoinConfigPath $blocksRoot
    }
    if ($BackfillHeight -ge 0) {
        [void] $config.Remove('enterprisebootstrapfrompostgres')
        $config['enterprisebackfillheight'] = [string] $BackfillHeight
    }
    return $config
}

function Write-RuntimeConfig {
    $expected = Get-ExpectedConfig
    $lines = @(
        '# Generated by contrib/devtools/enterprise_pg17_runtime.ps1.'
        '# A fresh datadir is used; do not load an assumeutxo snapshot into it.'
    )
    foreach ($entry in $expected.GetEnumerator()) {
        $lines += "$($entry.Key)=$($entry.Value)"
    }
    $temporary = "$configPath.tmp-$PID"
    $lines | Set-Content -LiteralPath $temporary -Encoding utf8
    Move-Item -LiteralPath $temporary -Destination $configPath -Force
}

function Backup-RuntimeConfig {
    if (-not (Test-Path -LiteralPath $configPath -PathType Leaf)) {
        return $null
    }
    $backupDirectory = Join-Path $mainnetRoot 'config-backups'
    [void] (New-Item -ItemType Directory -Path $backupDirectory -Force)
    $backupPath = Join-Path $backupDirectory (
        'bitcoin-{0}.conf' -f [DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssZ')
    )
    Copy-Item -LiteralPath $configPath -Destination $backupPath
    return $backupPath
}

function Read-RuntimeConfig {
    if (-not (Test-Path -LiteralPath $configPath -PathType Leaf)) {
        throw "bitcoin.conf is missing: $configPath"
    }
    $values = @{}
    foreach ($line in [System.IO.File]::ReadAllLines($configPath)) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
        if ($trimmed -notmatch '^([^=]+)=(.*)$') { throw 'bitcoin.conf contains an invalid line.' }
        $key = $Matches[1].Trim()
        if ($values.ContainsKey($key)) { throw "bitcoin.conf contains duplicate key: $key" }
        $values[$key] = $Matches[2].Trim()
    }
    return $values
}

function Test-RuntimeLayout {
    foreach ($path in @($mainnetRoot, $nodeDirectory, $blocksRoot, $runtimeEnv, $configPath)) {
        if (-not (Test-Path -LiteralPath $path)) { throw "Runtime path is missing: $path" }
    }
    [void] (Import-EnterprisePgEnv -Path $runtimeEnv -ExpectedDatabase $ExpectedDatabase)
    Assert-EnterpriseSecretAcl -Path $sourceEnv
    Assert-EnterpriseSecretAcl -Path $runtimeEnv

    $actual = Read-RuntimeConfig
    $expected = Get-ExpectedConfig
    foreach ($entry in $expected.GetEnumerator()) {
        if (-not $actual.ContainsKey($entry.Key) -or $actual[$entry.Key] -cne $entry.Value) {
            throw "bitcoin.conf does not have the expected $($entry.Key) setting."
        }
    }
    $unexpected = @($actual.Keys | Where-Object { -not $expected.Contains($_) })
    if ($unexpected.Count -ne 0) {
        throw "bitcoin.conf contains unexpected settings: $($unexpected -join ', ')"
    }
    Write-Output 'Runtime layout, configuration, and secret ACLs verified.'
    Write-Output "Expected spool path: $spoolPath"
}

switch ($Action) {
    'Preflight' {
        Write-Output 'Validated .env structure without displaying any values.'
        Write-Output "Runtime root: $runtimeRoot"
        Write-Output "Backfill height: $(if ($BackfillHeight -ge 0) { $BackfillHeight } else { 'disabled' })"
    }
    'Initialize' {
        if (-not $ConfirmInitialize) { throw 'Initialize requires -ConfirmInitialize.' }
        if ((Test-Path -LiteralPath (Join-Path $nodeDirectory 'blocks')) -or
            (Test-Path -LiteralPath (Join-Path $nodeDirectory 'chainstate')) -or
            (Test-Path -LiteralPath (Join-Path $blocksRoot 'blocks'))) {
            throw 'Runtime chain data already exists; refusing to reinitialize or overwrite it.'
        }
        foreach ($path in @(
            $nodeDirectory,
            $blocksRoot,
            (Join-Path $runtimeRoot 'artifacts'),
            (Join-Path $runtimeRoot 'postgres\secrets'),
            (Join-Path $runtimeRoot 'postgres\backups'),
            (Join-Path $runtimeRoot 'postgres\migrations'),
            (Join-Path $runtimeRoot 'postgres\logs')
        )) {
            [void] (New-Item -ItemType Directory -Path $path -Force)
        }
        Protect-EnterpriseSecretFile -Path $sourceEnv
        Protect-EnterpriseDirectory -Path $mainnetRoot
        if ((Test-Path -LiteralPath $configPath) -and -not $ForceConfig) {
            throw 'bitcoin.conf already exists; use -ForceConfig only to replace configuration, never chain data.'
        }
        Copy-Item -LiteralPath $sourceEnv -Destination $runtimeEnv -Force
        Protect-EnterpriseSecretFile -Path $runtimeEnv
        Write-RuntimeConfig
        Test-RuntimeLayout
        Write-Output 'Runtime initialized. No node process was started.'
    }
    'Verify' {
        Test-RuntimeLayout
    }
    'Configure' {
        if (-not $ConfirmConfigUpdate) { throw 'Configure requires -ConfirmConfigUpdate.' }
        foreach ($path in @($nodeDirectory, $blocksRoot, $runtimeEnv)) {
            if (-not (Test-Path -LiteralPath $path)) { throw "Runtime path is missing: $path" }
        }
        if ((Test-Path -LiteralPath $configPath) -and -not $ForceConfig) {
            throw 'bitcoin.conf exists; use -ForceConfig with the explicit config-update confirmation.'
        }
        Assert-EnterpriseSecretAcl -Path $runtimeEnv
        $backupPath = Backup-RuntimeConfig
        Write-RuntimeConfig
        Test-RuntimeLayout
        if ($backupPath) {
            Write-Output "Previous runtime configuration retained at: $backupPath"
        }
        Write-Output 'Runtime configuration updated. No node process was started.'
    }
    'LaunchCommand' {
        Test-RuntimeLayout
        if (-not $BitcoindPath) { throw 'LaunchCommand requires -BitcoindPath.' }
        $binary = (Resolve-Path -LiteralPath $BitcoindPath -ErrorAction Stop).Path
        $versionOutput = @(& $binary "-datadir=$nodeDirectory" -version 2>&1)
        $versionExitCode = $LASTEXITCODE
        $version = $versionOutput | Select-Object -First 1
        if ($versionExitCode -ne 0 -or -not $version -or $version -match 'dirty') {
            throw 'The staged bitcoind version is unavailable or contains dirty.'
        }
        Write-Output 'Run this command manually after migration acceptance:'
        Write-Output "& '$binary' '-datadir=$nodeDirectory'"
    }
}
